define([], function() {
  return {
    'titlePlaceholder': 'Title',
    'queryPlaceholder': 'Query(KQL)',
    'emptyDropDownPlaceholder': '(Not selected)',
    'connectorPlaceholder': 'Connector name',
    'fieldPlaceholder': 'Field name',
    'entityTypeLabel': 'Entity type',
    'connectorLabel': 'Connector',
    'queryLabel': 'Query',
    'usefulQueryLabel': 'Useful query',
    'fieldLabel': 'Field',
    'addButtonText': 'Add',
    'searchButtonText': 'Search',
    'entityTypeOptionSite': 'site',
    'entityTypeOptionList': 'list',
    'entityTypeOptionDrive': 'drive',
    'entityTypeOptionListItem': 'listItem',
    'entityTypeOptionDriveItem': 'driveItem',
    'entityTypeOptionMessage': 'message',
    'entityTypeOptionEvent': 'event',
    'entityTypeOptionExternalItem': 'externalItem',
    'usefulQueryOptionSites': 'Sites',
    'usefulQueryOptionApps': 'List and Library',
    'usefulQueryOptionNews': 'News',
    'usefulQueryOptionListItems': 'List items',
    'usefulQueryOptionDocuments': 'Documents',
    'usefulQueryOptionPeople': 'People',
    'responseBodyPivotLabel': 'Response body',
    'responseHeadersPivotLabel': 'Response header'
  }
});